from __future__ import annotations

"""Evaluate event-lattice candidate ranking on real-score semantic measures.

The input MusicXML is treated as ground truth, then controlled OMR-like corruptions are
applied. This is not a scan-recognition benchmark; it checks whether the bounded
calibrator improves candidate recovery on music not generated by the training script.
"""

import argparse
import json
import random
import sys
from dataclasses import replace
from fractions import Fraction
from pathlib import Path

from lxml import etree

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from scorescan.event_calibration import EventCalibrator, agreement_profiles  # noqa: E402
from scorescan.score_ir import MeasureIR, PitchIR, measure_distance, score_from_tree  # noqa: E402
from scorescan.util import atomic_write_json  # noqa: E402
from scorescan.variant_family import variant_family  # noqa: E402


def mutate(measure: MeasureIR, kind: str, rng: random.Random) -> MeasureIR:
    notes = list(measure.notes)
    regular_indices = [index for index, note in enumerate(notes) if not note.grace]
    if not regular_indices:
        return measure
    index = rng.choice(regular_indices)
    note = notes[index]
    if kind == "octave" and note.pitch:
        notes[index] = replace(note, pitch=replace(note.pitch, octave=max(1, min(8, note.pitch.octave + rng.choice((-1, 1))))))
    elif kind == "step" and note.pitch:
        steps = [value for value in "CDEFGAB" if value != note.pitch.step]
        notes[index] = replace(note, pitch=replace(note.pitch, step=rng.choice(steps)))
    elif kind == "duration":
        notes[index] = replace(note, duration=max(Fraction(1, 16), note.duration * rng.choice((Fraction(1, 2), Fraction(2)))))
    elif kind == "delete" and len(regular_indices) > 1:
        notes.pop(index)
    elif kind == "extra":
        notes.insert(index, replace(note, onset=note.onset + Fraction(1, 16)))
    elif kind == "voice":
        notes[index] = replace(note, voice="2")
    elif kind == "rest":
        notes[index] = replace(note, rest=not note.rest, pitch=None if not note.rest else PitchIR("C", Fraction(0), 4))
    return replace(measure, notes=tuple(notes))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("references", nargs="+", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--seed", type=int, default=20260716)
    args = parser.parse_args()
    rng = random.Random(args.seed)
    calibrator = EventCalibrator()
    baseline_correct = model_correct = groups = 0
    by_file: list[dict[str, object]] = []
    for path in args.references:
        tree = etree.parse(str(path), etree.XMLParser(resolve_entities=False, no_network=True))
        score = score_from_tree(tree)
        file_groups = file_base = file_model = 0
        for reference in score.measures:
            if not [note for note in reference.notes if not note.grace]:
                continue
            candidates = [reference, replace(reference, divisions=max(1, reference.divisions * 2))]
            correlated = mutate(reference, rng.choice(("duration", "delete", "extra", "voice")), rng)
            candidates.extend([correlated, correlated, correlated])
            candidates.extend([mutate(reference, rng.choice(("octave", "step", "rest")), rng) for _ in range(2)])
            variants = ("primary", "flat", "deblock", "otsu", "adaptive", "upscale", "staffnorm")
            profiles = agreement_profiles(
                candidates,
                [variant_family(variant) for variant in variants],
            )
            baseline = max(range(len(candidates)), key=lambda index: (profiles[index].mean_alignment_similarity, profiles[index].median_alignment_similarity, -index))
            model = max(range(len(candidates)), key=lambda index: (calibrator.predict_probability(profiles[index]), profiles[index].mean_alignment_similarity, -index))
            baseline_ok = measure_distance(reference, candidates[baseline]) <= 0.002
            model_ok = measure_distance(reference, candidates[model]) <= 0.002
            groups += 1
            file_groups += 1
            baseline_correct += int(baseline_ok)
            model_correct += int(model_ok)
            file_base += int(baseline_ok)
            file_model += int(model_ok)
        by_file.append({
            "file": path.name,
            "groups": file_groups,
            "baseline_top1": file_base / max(file_groups, 1),
            "model_top1": file_model / max(file_groups, 1),
        })
    report = {
        "model_version": calibrator.model_version,
        "seed": args.seed,
        "groups": groups,
        "baseline_top1": baseline_correct / max(groups, 1),
        "model_top1": model_correct / max(groups, 1),
        "by_file": by_file,
        "scope": "real MusicXML measures with controlled semantic corruptions and production family balancing; not end-to-end scan OMR",
    }
    atomic_write_json(args.output, report)
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
