from __future__ import annotations

from pathlib import Path

import pytest
from PIL import Image

from app.tools.prepare_openscore_svg_regions import (
    SVG_CLASS_TO_CATEGORY,
    _render_score,
    _tile_page,
    clip_small_page_overflow,
    parse_matrix,
    parse_view_box,
    path_bbox,
    polyline_bbox,
    semantic_svg_objects,
    svg_class_objects,
    split_for_source,
)


def test_parse_view_box_and_matrix_transform() -> None:
    assert parse_view_box("0 0 100.5 200") == (0, 0, 100.5, 200)
    assert parse_matrix("matrix(2,0,0,3,10,20)") == (2, 0, 0, 3, 10, 20)


def test_path_bbox_handles_implicit_lines_and_affine_transform() -> None:
    assert path_bbox(
        "M0,0 10,0 L10,5 L0,5 Z",
        matrix=parse_matrix("matrix(2,0,0,3,10,20)"),
    ) == (10, 20, 30, 35)


def test_path_bbox_uses_cubic_extrema_not_control_point_extrema() -> None:
    # Control points reach y=10, but this symmetric curve reaches y=7.5.
    box = path_bbox("M0,0 C0,10 10,10 10,0")
    assert box == pytest.approx((0, 0, 10, 7.5))


def test_polyline_bbox_expands_for_scaled_stroke() -> None:
    box = polyline_bbox(
        "0,10 100,10",
        matrix=parse_matrix("matrix(2,0,0,2,0,0)"),
        stroke_width=2,
    )
    assert box == pytest.approx((-2, 18, 202, 22))


def test_parser_rejects_relative_or_future_svg_commands() -> None:
    with pytest.raises(ValueError, match="unsupported"):
        path_bbox("m0,0 l10,10")
    with pytest.raises(ValueError, match="unsupported"):
        path_bbox("M0,0 Q5,10 10,0")


def test_semantic_svg_objects_reads_exact_class_geometry(tmp_path: Path) -> None:
    svg = tmp_path / "page-1.svg"
    svg.write_text(
        """\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 50">
  <desc>Generated by test renderer</desc>
  <path class="SlurSegment" stroke-width="2"
        d="M10,20 C20,10 40,10 50,20"/>
  <path class="Page" d="M0,0 L100,0 L100,50 L0,50 Z"/>
</svg>
""",
        encoding="utf-8",
    )
    view_box, objects, renderer, excluded = semantic_svg_objects(svg)
    assert view_box == (0, 0, 100, 50)
    assert renderer == "Generated by test renderer"
    assert excluded == {}
    assert len(objects) == 1
    assert objects[0]["category"] == "slur"
    assert objects[0]["box_xyxy"] == pytest.approx([9, 11.5, 51, 21])


def test_explicit_svg_class_geometry_does_not_expand_semantic_mapping(
    tmp_path: Path,
) -> None:
    svg = tmp_path / "page-1.svg"
    svg.write_text(
        """\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 50">
  <desc>Generated by test renderer</desc>
  <path class="Note" d="M20,20 L30,20 L30,28 L20,28 Z"/>
  <path class="StaffLines" d="M5,10 L95,10 L95,30 L5,30 Z"/>
  <path class="Dynamic" d="M40,35 L60,35 L60,45 L40,45 Z"/>
</svg>
""",
        encoding="utf-8",
    )

    view_box, objects, renderer, excluded = svg_class_objects(
        svg,
        {"Note", "StaffLines"},
    )

    assert view_box == (0, 0, 100, 50)
    assert renderer == "Generated by test renderer"
    assert excluded == {}
    assert [(row["svg_class"], row["category"]) for row in objects] == [
        ("Note", "Note"),
        ("StaffLines", "StaffLines"),
    ]
    assert "Note" not in SVG_CLASS_TO_CATEGORY
    assert "StaffLines" not in SVG_CLASS_TO_CATEGORY


def test_explicit_svg_class_geometry_rejects_empty_allowlist(
    tmp_path: Path,
) -> None:
    svg = tmp_path / "page-1.svg"
    svg.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"/>',
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="at least one"):
        svg_class_objects(svg, {"", "  "})


def test_piece_split_is_deterministic_and_validates_fractions() -> None:
    first = split_for_source(
        "composer/work/score.mscx",
        calibration_fraction=0.1,
        test_fraction=0.15,
    )
    second = split_for_source(
        "COMPOSER\\WORK\\SCORE.MSCX",
        calibration_fraction=0.1,
        test_fraction=0.15,
    )
    assert first == second
    assert first in {"train", "calibration", "test"}
    with pytest.raises(ValueError):
        split_for_source(
            "score.mscx",
            calibration_fraction=0.5,
            test_fraction=0.5,
        )


def test_clips_small_renderer_edge_bleed_but_rejects_bad_geometry() -> None:
    assert clip_small_page_overflow(
        (-8, 100, 580, 140),
        (0, 0, 2977, 4208),
    ) == (0, 100, 580, 140)
    with pytest.raises(ValueError, match="materially outside"):
        clip_small_page_overflow(
            (-500, 100, 580, 140),
            (0, 0, 2977, 4208),
        )


def test_semantic_parser_excludes_materially_page_clipped_objects(
    tmp_path: Path,
) -> None:
    svg = tmp_path / "page-1.svg"
    svg.write_text(
        """\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 50">
  <path class="MeasureNumber" d="M-30,10 L10,10 L10,20 L-30,20 Z"/>
  <path class="Dynamic" d="M-0.5,30 L20,30 L20,40 L-0.5,40 Z"/>
</svg>
""",
        encoding="utf-8",
    )

    _view_box, objects, _renderer, excluded = semantic_svg_objects(svg)

    assert excluded == {"measureNumberText": 1}
    assert len(objects) == 1
    assert objects[0]["category"] == "genericDynamic"
    assert objects[0]["box_xyxy"] == [0, 30, 20, 40]


def test_semantic_mapping_covers_in_scope_common_piano_and_ensemble_marks() -> None:
    expected = {
        "Arpeggio": "arpeggio",
        "Breath": "breathMark",
        "Expression": "expressionText",
        "Fermata": "fermata",
        "Fingering": "fingeringText",
        "GlissandoSegment": "glissando",
        "OttavaSegment": "ottava",
        "PedalSegment": "pedal",
        "RehearsalMark": "rehearsalMarkText",
        "StaffText": "staffText",
        "StemSlash": "graceSlash",
        "SystemText": "systemText",
        "TextLineSegment": "textLine",
        "TremoloSingleChord": "tremoloSingle",
        "TremoloTwoChord": "tremoloBetweenNotes",
        "TrillSegment": "trillExtension",
        "VoltaSegment": "volta",
    }
    assert {name: SVG_CLASS_TO_CATEGORY.get(name) for name in expected} == expected
    # Chord symbols/functional harmony remain explicitly outside the product
    # accuracy boundary and must not silently enter the semantic detector.
    assert "Harmony" not in SVG_CLASS_TO_CATEGORY
    # Lyric semantics are also outside the frozen product boundary. MuseScore
    # renders lyrics with an exact, separate class, so they remain useful
    # detector background without contaminating generic score-text positives.
    assert "Lyrics" not in SVG_CLASS_TO_CATEGORY
    assert "LyricsLineSegment" not in SVG_CLASS_TO_CATEGORY


def test_empty_tiles_are_retained_as_deterministic_negative_controls(
    tmp_path: Path,
) -> None:
    pages = tmp_path / "pages"
    pages.mkdir()
    svg = pages / "page-1.svg"
    png = pages / "page-1.png"
    svg.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 100">'
        "<desc>test</desc></svg>",
        encoding="utf-8",
    )
    Image.new("RGB", (200, 100), "white").save(png)

    rows, dropped, excluded, negative_count = _tile_page(
        split="train",
        source_key="piece.mscx",
        svg_path=svg,
        png_path=png,
        output_dir=tmp_path,
        categories={"slur": 1},
        tile_size=100,
        overlap=0,
        minimum_fraction=0.8,
        negative_ratio=1.0,
    )

    assert len(rows) == 2
    assert all(row["objects"] == [] for row in rows)
    assert negative_count == 2
    assert dropped == {}
    assert excluded == {}


def test_semantic_tile_clips_long_object_to_visible_crop(
    tmp_path: Path,
) -> None:
    pages = tmp_path / "pages"
    pages.mkdir()
    svg = pages / "page-1.svg"
    png = pages / "page-1.png"
    svg.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 200">'
        '<path class="SlurSegment" stroke-width="2" '
        'd="M50,100 C300,20 900,20 1150,100"/></svg>',
        encoding="utf-8",
    )
    Image.new("RGB", (1200, 200), "white").save(png)

    rows, dropped, _excluded, _negative_count = _tile_page(
        split="train",
        source_key="piece.mscx",
        svg_path=svg,
        png_path=png,
        output_dir=tmp_path,
        categories={"slur": 1},
        tile_size=1024,
        overlap=256,
        minimum_fraction=0.8,
        negative_ratio=0.0,
        long_span_minimum_fraction=0.25,
    )

    assert dropped == {}
    positive = next(row for row in rows if row["objects"])
    box = positive["objects"][0]["box_xyxy"]
    assert 0 <= box[0] < box[2] <= 1024
    assert 0 <= box[1] < box[3] <= 200
    assert positive["objects"][0]["page_box_xyxy"][2] > box[2]
    assert len(positive["objects"][0]["source_object_id"]) == 24
    assert (
        positive["objects"][0]["target_geometry_provenance"]
        == "complete-page-svg-geometry-before-tile-clipping@1"
    )


def test_render_score_repairs_only_incomplete_piece_pages(
    tmp_path: Path,
    monkeypatch,
) -> None:
    piece_dir = tmp_path / "pages" / "piece"
    piece_dir.mkdir(parents=True)
    (piece_dir / "page-1.svg").write_text("stale svg", encoding="utf-8")
    (piece_dir / "page-1.png").write_bytes(b"stale png")
    (piece_dir / "page-2.svg").write_text("partial svg", encoding="utf-8")
    sibling = piece_dir.parent / "other-piece"
    sibling.mkdir()
    protected = sibling / "page-1.svg"
    protected.write_text("keep", encoding="utf-8")

    calls: list[str] = []

    def fake_run(command, **_kwargs):
        output = Path(command[2])
        calls.append(output.suffix)
        for page in (1, 2):
            rendered = piece_dir / f"page-{page}{output.suffix}"
            if output.suffix == ".svg":
                rendered.write_text(f"fresh {page}", encoding="utf-8")
            else:
                rendered.write_bytes(f"fresh {page}".encode())

    monkeypatch.setattr(
        "app.tools.prepare_openscore_svg_regions.subprocess.run",
        fake_run,
    )

    pages = _render_score(
        tmp_path / "score.mscx",
        musescore_exe=tmp_path / "MuseScore.exe",
        piece_dir=piece_dir,
        timeout_seconds=30,
    )

    assert calls == [".svg", ".png"]
    assert [svg.name for svg, _png in pages] == ["page-1.svg", "page-2.svg"]
    assert [png.name for _svg, png in pages] == ["page-1.png", "page-2.png"]
    assert (piece_dir / "page-1.svg").read_text(encoding="utf-8") == "fresh 1"
    assert protected.read_text(encoding="utf-8") == "keep"
